### ISSUE TITLE
Add install as a TaskDefinition

### ISSUE THREAD

**Issue by mkaes** [mesonbuild/vscode-meson#100]
Currently the TaskDefinitions that can be called are:
build, configure, reconfigure, clean, run unit tests and run benchmarks.
An option to call meson install would be a nice improvement

**Comment by tristan957** [comment]
Could you submit a PR? Seemingly it would not be too difficult

**Comment by mkaes** [comment]
I created #102.
I think it works, but this is the first time I work on a vs code extension.

**Comment by mkaes** [comment]
Since the pr #102 is accepted we can close this
