### ISSUE TITLE
[feature request] Support `sourcedir` beneath the workspace root for `meson setup`

### ISSUE THREAD

**Issue by starthal** [mesonbuild/vscode-meson#101]
The configuration options allow the user to pass additional keyword arguments to `meson setup`. But it always calls the command with only the `builddir` positional argument. 

Would it be difficult to support the `sourcedir` argument as well? Would this break other parts of the extension?

The use case is a workspace with a single `meson.build`, but that file is under a subdirectory 'tests'. (The meson build is only used for unit testing; a proprietary build system for the rest of the project). On the command line I can invoke `meson setup tests/builddir tests/sourcedir` from the root.

Ref: https://mesonbuild.com/Commands.html#setup

**Comment by tristan957** [comment]
This seems pretty reasonable. Can you submit a PR?

**Comment by starthal** [comment]
I found #22 which should do it. I don't know TypeScript but I'll see if I can fix conflicts and try it when I get a chance.

**Comment by tristan957** [comment]
@starthal that would be great. Thanks!

**Comment by starthal** [comment]
I've since moved `meson.build` to the root and *politely but sternly* instructed the top-level build system to ignore it.

But I believe #179 resolves this.
