### ISSUE TITLE
Latest muon causes syntax errors in unrelated files

### ISSUE THREAD

**Issue by medhefgo** [mesonbuild/vscode-meson#124]
vscode-meson generates tons of syntax errors for any open files that aren't meson build files (any c source file or settings.json would do) if the muon linter is enabled in the settings. This seems to happen since muon commit [b60b5196](https://git.sr.ht/~lattis/muon/commit/b60b51965f74e0aefb774e4adb46f477c7d0eb56).

**Comment by dcbaker** [comment]
@annacrombie

**Comment by tristan957** [comment]
![image](https://user-images.githubusercontent.com/11936772/232147456-c57737e7-c15e-495a-8b33-a565d2fda537.png)

One of the syntax errors I see: `unexpected character: '"'`

**Comment by annacrombie** [comment]
Should be fixed by #131 I think.  The bug was that this plugin was running muon analyze on all of your files.  It didn't cause any issues with older versions of muon since in those versions unrecognized files were just ignored.
