### ISSUE TITLE
Initial configuration failure:  mesonbuild.reconfigure command not found on first setup

### ISSUE THREAD

**Issue by olmaisomfy** [mesonbuild/vscode-meson#155]
When opening a meson project for the first time (so not configured at all);

Trying to run `Meson: reconfigure` result in an error message `command 'mesonbuild.reconfigure' command not found`.
Regression has been introduced in commit https://github.com/mesonbuild/vscode-meson/commit/5ddca809784bf076344584847a589aa2c5f30633 . `rebuildTests`, in the extension init, never finish.

**Comment by tristan957** [comment]
@ylatuya can you help out on this?
