### ISSUE TITLE
lots of errors with gstreamer repo

### ISSUE THREAD

**Issue by gdesmott** [mesonbuild/vscode-meson#159]
Getting lots of error when opening the `gstreamer` mono-repo. I've been told by @xclaesse it's related to the new language server feature.

![Screenshot from 2023-10-18 14-16-02](https://github.com/mesonbuild/vscode-meson/assets/1379524/f4f37c91-4fc8-430d-ad6b-5f583d6c087a)

**Comment by gdesmott** [comment]
Changing this setting removes those errors: 
![image](https://github.com/mesonbuild/vscode-meson/assets/1379524/e9ca7db6-4636-411f-962b-ac4f538ea1ba)

**Comment by tristan957** [comment]
cc @JCWasmx86

**Comment by tristan957** [comment]
Given what you said, I don't really see a reason to change anything. Sounds like gstreamer might need to update some subprojects.

**Comment by tristan957** [comment]
@JCWasmx86 not sure if you noticed the typo in the errors above: `No method has found`

**Comment by tristan957** [comment]
Oh, guess I read that message wrong.

**Comment by tristan957** [comment]
Yeah that looks like a gstreamer bug again.

**Comment by tristan957** [comment]
Closing this. Thanks @JCWasmx86
