### ISSUE TITLE
[Feature] syntax-highlight of fstrings

### ISSUE THREAD

**Issue by bruchar1** [mesonbuild/vscode-meson#160]
It would be great if `@subs@` parts of f-strings were highlighted with a different color, as well as `@0@` parts in regular strings.
Special substitutions in functions like `custom_target` could be highlighted as well (e.g. `@INPUT@`)

**Comment by tristan957** [comment]
Textmate language definitions are the worst...

**Comment by tristan957** [comment]
Yep. I am just expressing my discontent with VSCode's inaction to support Tree Sitter.
