### ISSUE TITLE
How to set build dir

### ISSUE THREAD

**Issue by srobertjames** [mesonbuild/vscode-meson#161]
The extension tries to build in `builddir`.  However, I want to build in `build/debug` or `build/release`.

At the Meson command line, this is is set via `-C`.  How can I set in the vscode tasks extension?

**Comment by tristan957** [comment]
You could try with mesonbuild.configureOptions, but I am not sure. We might not support this.

**Comment by srobertjames** [comment]
What setting should I put there? The ones I've tried give a jsonc error `Value expected`.

**Comment by tristan957** [comment]
"mesonbuild.buildFolder" is the setting
