### ISSUE TITLE
Path issue when using cygwin as vscode integrated console on Windows

### ISSUE THREAD

**Issue by ZZH-Finzlize** [mesonbuild/vscode-meson#203]
I'm using cygwin as vscode integrated console, but I found when I update this extension to version 1.8.1, it can't reconfigure my project any more, then I back to version 1.8.0. and that version has no problem.

v1.8.1:
![image](https://github.com/mesonbuild/vscode-meson/assets/33342565/a135ab06-47a6-4ee6-8ce7-2c9ad0fb7592)

v1.8.0:
![image](https://github.com/mesonbuild/vscode-meson/assets/33342565/e1f81cf7-9d30-465e-b016-8667eb7ee6e4)

**Comment by tristan957** [comment]
Could you bisect the commit which broke it for you? I suspect that it might be https://github.com/mesonbuild/vscode-meson/commit/5a103c462f5a9d4e17bd9184e5b4fcfff3e1495c.

**Comment by tristan957** [comment]
Does https://github.com/mesonbuild/vscode-meson/commit/3946f91725743a3b3ab0b0c37bb9368de8c82de1 work for you?

**Comment by ZZH-Finzlize** [comment]
I guess https://github.com/mesonbuild/vscode-meson/commit/5a103c462f5a9d4e17bd9184e5b4fcfff3e1495c should be the reason, because of the command is different between two version, in version 1.8.0 it is "meson.exe" but in 1.8.1 it is "bash -c meson ....."

**Comment by tristan957** [comment]
What does Meson resolve to in the broken command?

**Comment by ZZH-Finzlize** [comment]
I think this problem is nothing to do with the Meson, Meson raise a error says "ERROR: Neither source directory 'd:workprojw3000stm32onboard-V3builddir' nor build directory 'd:workprojw3000stm32onboard-V3' exist.", clearly the "\" chars in the path are wrapped by "bash" as Escape character, bash is a linux shell so it accept Unix style path.

So could we add a setting to select the "ProcessExecution" or "ShellExecution"?

**Comment by lukester1975** [comment]
Maybe https://github.com/lukester1975/vscode-meson/tree/more-shell-fixes ?

I successfully expunged cygwin from my life a few years ago so haven't checked it and I refuse to go back... OK on Linux/bash, Windows/cmd and Windows/git bash for me though.

There are the `ShellQuoting` options for each argument if not. Maybe one does the trick.

**Comment by tristan957** [comment]
What you are proposing looks reasonable

**Comment by tristan957** [comment]
Fixed in 1.19.1
