### ISSUE TITLE
Plugin updates entry in `settings.json` with absolute path

### ISSUE THREAD

**Issue by Lykkeberg** [mesonbuild/vscode-meson#211]
The Meson plugin is changing the `"C_Cpp.default.compileCommands"` to include an absolute path, when opening the project in VSCode. This makes it impossible to have the `.vscode/settings.json` file under version control using ie. Git.

The offending line in the code:
https://github.com/mesonbuild/vscode-meson/blob/740b499a3b9ae841e4dc005fcad4c6afc5d6df80/src/extension.ts#L139

It might be an idea to have this be a relative path or a path string using environment varables?

**Comment by tristan957** [comment]
I am thinking the solution here is https://github.com/mesonbuild/vscode-meson/pull/210/commits/7967d386e6d17658a3e55d298c702930eece5f18.

**Comment by xclaesse** [comment]
Something like https://github.com/mesonbuild/vscode-meson/commit/7967d386e6d17658a3e55d298c702930eece5f18 would be nice indeed. My use-case is I have a project where we commit `.vscode/settings.json` in the git repository, so when vscode-meson changes some settings it creates a diff  that would be committed if I blindly do "git commit -a". For that project we can include predefined settings in the file we commit and vscode-meson does not need to change them:
```
    "mesonbuild.buildFolder": "build",
    "C_Cpp.default.compileCommands": "${workspaceRoot}/${mesonbuild.buildFolder}/compile_commands.json",
```

@tristan957 did you open a PR with that yet? I wasn't sure if we want 3 different settings, or a single "don't touch my settings" boolean?

**Comment by tristan957** [comment]
I think separate settings is probably for the best. I didn't pluck that commit out, but I could. Let work on that.

**Comment by xclaesse** [comment]
> Are they relative to the workspace directory or the source directory?

And I don't think we can even use `${workspaceRoot}/${mesonbuild.buildFolder}` in the case of multiple folders workspace.

**Comment by tristan957** [comment]
We cannot. VSCode doesn't provide an API to do that interpolation anyway.

**Comment by xclaesse** [comment]
> We cannot. VSCode doesn't provide an API to do that interpolation anyway.

I think it does it for you, at least for those listed https://code.visualstudio.com/docs/editor/variables-reference. Not sure it works for ${mesonbuild.buildFolder} in this context, I haven't tested that yet.

**Comment by tristan957** [comment]
> Visual Studio Code supports variable substitution in [Debugging](https://code.visualstudio.com/docs/editor/debugging) and [Task](https://code.visualstudio.com/docs/editor/tasks) configuration files as well as some select settings. Variable substitution is supported inside some key and value strings in launch.json and tasks.json files using ${variableName} syntax.

It does not. See https://github.com/mesonbuild/vscode-meson/issues/130.

**Comment by tristan957** [comment]
Closing this now. v1.21.0 has a fix. Set `mesonbuild.modifySettings` to false or an array not including `ms-vscode.cpptools`.
