### ISSUE TITLE
VSCode path variables not expanded

### ISSUE THREAD

**Issue by liam-clink** [mesonbuild/vscode-meson#220]
I put both the muon and MesonLSP binaries in my project folder for convenience. However, the plugin invokes them incorrectly, the variable isn't expanded correctly. This is the error that I'm getting:

```
[Error - 12:15:35 AM] Meson Language Server (Swift-MesonLSP) client: couldn't create connection to server.
Launching server using command /${workspaceFolder}/mesonlsp failed. Error: spawn /${workspaceFolder}/mesonlsp ENOENT
```

There's probably an API for VSCode extensions that requests translation of this sort.

This is the list of built in variables: https://code.visualstudio.com/docs/editor/variables-reference

**Comment by liam-clink** [comment]
This is an example of a question related to this that I found: https://stackoverflow.com/questions/43972354/how-can-an-extension-expand-configuration-variables-in-vscode

**Comment by tristan957** [comment]
There is no such API

**Comment by tristan957** [comment]
Closing as a duplicate: https://github.com/mesonbuild/vscode-meson/issues/130
