### ISSUE TITLE
Extention doesn't activate if meson.build is not in the workspace root

### ISSUE THREAD

**Issue by intractabilis** [mesonbuild/vscode-meson#234]
Because of the Perforce specifics, I can't have `meson.build` in the workspace root. My `meson.build` is at `${workspaceFolder}/src`. In this configuration, the Meson extension doesn't even start. There are no Meson commands, and there is no Meson section in the OUTPUT console. In the Extension Host's section of the OUTPUT console, I see
```
2024-05-16 20:22:01.728 [info] ExtensionService#_doActivateExtension mesonbuild.mesonbuild, startup: false, activationEvent: 'onLanguage:meson'
```
That's it. I tried to cleanly remove the extension and reinstall it. No effect.

Meson extension version is 1.24.0.
VS Code 1.89.1.
OS Linux.

**Comment by tristan957** [comment]
It definitely should activate if you have a meson file anywhere: https://github.com/mesonbuild/vscode-meson/blob/main/package.json#L42

**Comment by intractabilis** [comment]
> It definitely should activate if you have a meson file anywhere: https://github.com/mesonbuild/vscode-meson/blob/main/package.json#L42

Should I believe my eyes?

![изображение](https://github.com/mesonbuild/vscode-meson/assets/45959195/7d8644c6-c112-4ed3-af80-6b8f150b9a51)

**Comment by intractabilis** [comment]
Can you give some advice on how I can help debug this?

**Comment by tristan957** [comment]
Could you post your file structure or a minimal reproducible tarball?

**Comment by intractabilis** [comment]
I guess I can't. It works in small projects. My workspace folder has 2.5 million files in total. If I copy just Meson files into an empty workspace (preserving Meson files' directory structure), I can see the activation string in the Extension Host's section of the OUTPUT console:
```
mesonbuild.mesonbuild, startup: true, activationEvent: 'workspaceContains:**/meson.build'
```
In my original workspace, I observe:
```
mesonbuild.mesonbuild, startup: false, activationEvent: 'onLanguage:meson'
```
and the extension doesn't work.

So, maybe VS Code chokes up on `workspaceContains:**/meson.build`.

**Comment by tristan957** [comment]
So the onLanguage:meson isn't working when you open a meson.build file? That is weird.

**Comment by intractabilis** [comment]
> So the onLanguage:meson isn't working when you open a meson.build file? That is weird.

Yes, I agree.

**Comment by tristan957** [comment]
If that isn't happening, it's definitely a vscode issue, so I might start investigating on that side of things. I'm guessing it's just Electron choking on the amount of files in your workspace.

**Comment by intractabilis** [comment]
Probably. However, other extensions scan the workspace on VS Code start, too, and they work just fine. For example, [Task Explorer](https://marketplace.visualstudio.com/items?itemName=spmeesseman.vscode-taskexplorer) (though I have to admit, it takes a while to start).

Also, I don't think scanning the entire workspace on start is a good practice. Nowadays, in SW companies, everything is in the cloud. I accidentally had my project on a local disk for an experiment. In the past few years, in all the companies I worked at, the workspaces were NSF shares hosted on virtual machines in the cloud. I am terrified to see how scanning the entire workspace will look on an NSF share. Ironically, Meson itself prohibits scanning the file system because of performance considerations.

**Comment by tristan957** [comment]
It isn't the same. It activates on anything: https://github.com/spmeesseman/vscode-taskexplorer/blob/v2-production/package.json#L50-L52. I don't even think VSCode recommends this anymore. Pretty sure it's deprecated.

**Comment by intractabilis** [comment]
Ok, it seems like it scans the workspace after activation. Perhaps other extensions don't activate on a glob because of the performance drawback. I mean, people can open all kinds of directories in VS Code. For example, one can open a home directory, which may contain hundreds of projects, millions of files, mounted file systems over slow network, etc. `workspaceContains:**/meson.build` will cause VS Code to scan all of this just to decide if to activate an extension.

**Comment by tristan957** [comment]
Please propose better activation events.

**Comment by intractabilis** [comment]
> Please propose better activation events.

I am not savvy about developing VS Code extensions. However, the first thing that comes to my mind is whether it would be reasonable to limit the depth by two levels.

**Comment by tristan957** [comment]
Here are the docs: https://code.visualstudio.com/api/references/activation-events.

Here is how the CMake extension works: https://github.com/microsoft/vscode-cmake-tools/blob/main/package.json#L37-L67.

**Comment by intractabilis** [comment]
> Here is how the CMake extension works: https://github.com/microsoft/vscode-cmake-tools/blob/main/package.json#L37-L67.

It incorporates the exact idea I suggested: it limits the depth.

**Comment by tristan957** [comment]
Wanna make a PR?
