### ISSUE TITLE
Hide the sidebar icon when no meson.build files exist within the project

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/vscode-meson#26]
![image](https://user-images.githubusercontent.com/11936772/98186621-cca1fc00-1ed4-11eb-83ed-c79a4eb28b09.png)

This is in occurring in a Hugo project which definitely does not have any meson.build files.

**Comment by alanlivio** [comment]
I suggest "meson.activityBar.iconVisibility"

**Comment by alanlivio** [comment]
Other thing that may be hided is the notification ask to configure the project.
I suggest "meson.notificationOnOpen" (based in configureOnOpen).
