### ISSUE TITLE
Language server cache grows with no limite

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/vscode-meson#263]
My project has a subproject that takes a few GB of data. It seems every time the revision is changed in that subproject's wrap file a new copy of the whole source tree is added into the cache.

I believe the source tree should not be copied at all, the language server should use the checkout in-place in my workspace. If I edit a meson.build file in that subproject, I expect the linter to use that modified meson file instead of the cache copy anyway.

**Comment by tristan957** [comment]
Can you please move this to the language server repository? I'm not too sure what we could do here in the extension.

**Comment by xclaesse** [comment]
@tristan957 I didn't know there is another repo. Do you know where it is?

**Comment by tristan957** [comment]
On Tue Oct 22, 2024 at 3:50 PM CST, Xavier Claessens wrote:
> @tristan957 I didn't know there is another repo. Do you know where it is?

Yes, the repo is compute/compute-node.

-- 
Tristan Partin
https://tristan.partin.io

**Comment by xclaesse** [comment]
https://github.com/JCWasmx86/mesonlsp/issues/153
