### ISSUE TITLE
Moving this extension to the official meson project?

### ISSUE THREAD

**Issue by dcbaker** [mesonbuild/vscode-meson#38]
Hi, I'm on of the upstream meson developers, and a vscode user. This extension is the defacto standard for meson-vscode integration, and I'd really like to see it move forward, as a part of the meson project itself. Github has a feature that allows a repo to be transferred into a project, which helps with issues like forks continuing to point to the right place.

I believe that I would either have to be added as an owner of this repo, or the repo would first have to be transferred to me to be able to move it to the meson project. If you're interested please let me know.

**Comment by asabil** [comment]
Hi @dcbaker, thank you so much for suggesting this. I have unfortunately been unable to dedicate the time that this extension deserves.

I would indeed very much love to see this extension moved under the official Meson organization on GitHub as well as on the extension marketplace (if that's possible?).

Thank you again,
Ali

**Comment by dcbaker** [comment]
I haven't looked into the marketplace yet, but I'll co-ordinate with @jpakkane to see what we need to do to move the extensions. Likely you'll need to transfer the repo to one of us, and then we can move it into the organization. I don't seem to have the ability to create repos, but Jussi can either give me that permission or do the move himself

**Comment by dcbaker** [comment]
@asabil Jussi and I talked, I'll handle the move. I *think* the easiest way to do this is for you to transfer the repo to me, then I'll move it to the mesonbuild project space.

**Comment by asabil** [comment]
Excellent! I will initiate the transfer right away. What about the extension on the Marketplace?

**Comment by asabil** [comment]
Looks like you will need to rename/delete your existing fork before I can initiate the transfer

**Comment by dcbaker** [comment]
I deleted my fork

**Comment by asabil** [comment]
Just initiated the transfer, thank you again :)

**Comment by dcbaker** [comment]
Alright, this is done. Thanks!
