### ISSUE TITLE
run task failed with default layout in mesonbuild.configureOptions

### ISSUE THREAD

**Issue by godcrying** [mesonbuild/vscode-meson#6]
The default layout in mesonbuild.configureOptions is flat, the target file is in the meson-out folder. But when I run the "Meson: Run XXX" task, it try to run target file in build folder. So I got a "No such file" error.
When I modified layout to mirror, it worked fine.
I'm using the last release vscode.
Sorry for my weak English.

**Comment by asabil** [comment]
@SolarLiner any chance to have a look at this?

**Comment by SolarLiner** [comment]
I have tested that case before, and have fixed the bug... Or was I dreaming?

I'll look into this.

**Comment by dcbaker** [comment]
The default option was changed to mirror (as flat is now deprecated in meson upstream), should we go ahead and close this?

**Comment by xclaesse** [comment]
Let's close this.
