### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by Tachi107** [mesonbuild/vscode-meson#69]
Would it be possible to publish this extension to the Open VSX Registry? This would make it possible to install this extension on VSCode builds not provided by Microsoft ([VSCodium](https://vscodium.com), [`code`](https://archlinux.org/packages/community/x86_64/code/) on Arch Linux, etc)

I don't know if it can help, but the original [asabil.meson](https://open-vsx.org/extension/asabil/meson) extension was already there.

**Comment by dcbaker** [comment]
Yes, I’d love to be on openvsx as well. Since there are some bugs with the 1.4.0 release I think I’ll skip that and we’ll get the next release sorted for openvsx. I’ll assign this to myself to help me remember

**Comment by dcbaker** [comment]
Published here: https://open-vsx.org/extension/mesonbuild/mesonbuild

Will close when the action to auto-publish is merged

**Comment by Tachi107** [comment]
Nice, thanks!
