### ISSUE TITLE
Custom environment variables for meson configuration

### ISSUE THREAD

**Issue by MathiasMagnus** [mesonbuild/vscode-meson#9]
Meson requires `PKG_CONFIG_PATH` to find some dependencies, and even though I setup my PS profile to include this var, I cannot set it as the default shell, as it breaks many Linux tooling. Currently I can't seem to find a way to tell the extension to include extra env vars during the configuration step.

**Comment by tristan957** [comment]
This would probably be a pretty small PR if someone wanted to pick this up. I agree this would be a good nice to have.

**Comment by xclaesse** [comment]
Note that in the case of `PKG_CONFIG_PATH` you can instead add `pkg_config_path=/foo` configure option.

**Comment by ptomato** [comment]
I'd like to second this! My use case is a VSCodium session SSH'd into a Fedora Toolbox container. I'd like to be able to set the `DISPLAY` and `DBUS_SESSION_BUS_ADDRESS` environment variables when running Meson tests.

(For actually running the build product, you can set these environment variables in `launch.json`, but running tests doesn't take its environment variables from there. Also, I might expect it to respect the environment variables in the setting `terminal.integrated.env.linux`.)

I'd love to contribute this feature myself, if someone could give me a pointer on where to start. (I'm new to VSCode/VSCodium in general.) Would it be as simple as adding a configuration object to the `exec()` call in https://github.com/mesonbuild/vscode-meson/blob/10eb43d30a6d74c841abefca2597a33a900cf77e/src/tests.ts#L42?

**Comment by tristan957** [comment]
Hello Mr. gjs :)

If you look at that exec() function, it is using [`child_process.execFile`](https://nodejs.org/api/child_process.html#child_processexecfilefile-args-options-callback) behind the scenes. We just wrap it into a promise. You can see that there is an env variable located there. We don't spawn the process in an integrated terminal, so that setting would not work for us.

**Comment by ptomato** [comment]
Thanks very much! :smile: 

What would be a good place for the setting to live at, then? I'm not too familiar yet with VSCode so I don't really have a sense of this. Would it be a setting specific to the vscode-meson extension?

**Comment by tristan957** [comment]
It should go in the package.json file. Should be fairly obvious where to put it!
