### ISSUE TITLE
Can't build using extension after executable update

### ISSUE THREAD

**Issue by Skynerz** [mesonbuild/vscode-meson#91]
Hi,
For a reason, I had to reinstall meson (the executable). 
I used `pip install meson` and since, I didn't manage to build my projects by clicking on the <program>.elf in the extension view as it only show the following message in output view:
![image](https://user-images.githubusercontent.com/60877014/175076966-0e8b66b2-02d9-415b-bcf0-4eb102262a16.png)
and the progression pop-up shows a short time before disappearing without more details about the success or fail of the build... 

I tried running Meson: Configure but I get the message:
![image](https://user-images.githubusercontent.com/60877014/175070837-53b81ef3-e339-4b5e-afe1-3fdde07706db.png)

Running with command lines works fine.

Am I the only one having this kind of issue?
Thanks

Host OS: Win10
VSC version: 1.68.1
Meson: 0.62.2
Extension: 1.6.0

**Comment by Ongy** [comment]
You likely have to delete the build directory and re-create it.
Meson is a bit picky about the version of binary used to create it and version used to build.
But doesn't autofix it :/

The extension eats the error report somewhere, otherwise it should be obvious from meson output.

**Comment by Skynerz** [comment]
I did it several times with different scenarios:
- deleted the directory then `meson setup --cross-file arm-none-eabi.build build` -> I can use the "Meson: Reconfigure" command: everything in the terminal is going well but clicking on the .elf name just show the message `Building target tst\integrationAPI_mifare/tst_api_mifare.elf` and do nothing
- deleted the directory then tried the "Meson: Configure" command which gives the same message as in the first post
- deleted the directory, restarted VS Code then tried the "Meson: Configure" command which gives the same message as in the first post

Currently I can build using the commands, but it's not as convenient as it used to with the extension working well 🤔
I wonder if downgrading to a previous version of the Meson software could help?
